// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./../src/components/Button/src/AddButton.vue')['default'];
    BasicDialog: typeof import('./../src/components/Dialog/src/BasicDialog.vue')['default'];
    BasicFilterSearch: typeof import('./../src/components/Form/src/BasicFilterSearch.vue')['default'];
    BasicPagination: typeof import('./../src/components/Pagination/src/BasicPagination.vue')['default'];
    BasicTable: typeof import('./../src/components/Table/src/BasicTable.vue')['default'];
    CancelButton: typeof import('./../src/components/Button/src/CancelButton.vue')['default'];
    CloseIcon: typeof import('./../src/components/Icon/src/CloseIcon.vue')['default'];
    DangerButton: typeof import('./../src/components/Button/src/DangerButton.vue')['default'];
    Editor: typeof import('./../src/components/Editor/index.vue')['default'];
    EffectiveStatusText: typeof import('./../src/components/Text/src/EffectiveStatusText.vue')['default'];
    ElBadge: typeof import('element-plus/es')['ElBadge'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCarousel: typeof import('element-plus/es')['ElCarousel'];
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem'];
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElPagination: typeof import('element-plus/es')['ElPagination'];
    ElPopover: typeof import('element-plus/es')['ElPopover'];
    ElRadio: typeof import('element-plus/es')['ElRadio'];
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    ElTabPane: typeof import('element-plus/es')['ElTabPane'];
    ElTabs: typeof import('element-plus/es')['ElTabs'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    ElUpload: typeof import('element-plus/es')['ElUpload'];
    ExportButton: typeof import('./../src/components/Button/src/ExportButton.vue')['default'];
    ImportButton: typeof import('./../src/components/Button/src/ImportButton.vue')['default'];
    ImportDialog: typeof import('./../src/components/Dialog/src/ImportDialog.vue')['default'];
    Loading: typeof import('element-plus/es')['ElLoadingDirective'];
    PubDialog: typeof import('./../src/components/Dialog/src/PubDialog.vue')['default'];
    ResetButton: typeof import('./../src/components/Button/src/ResetButton.vue')['default'];
    SearchButton: typeof import('./../src/components/Button/src/SearchButton.vue')['default'];
    SlideVerify: typeof import('./../src/components/Verify/src/SlideVerify.vue')['default'];
    Src: typeof import('./../src/components/Loading/src/index.vue')['default'];
    StatusText: typeof import('./../src/components/Text/src/StatusText.vue')['default'];
    SvgIcon: typeof import('./../src/components/Icon/src/SvgIcon.vue')['default'];
    UploadBtn: typeof import('./../src/components/Upload/src/UploadBtn.vue')['default'];
  }
}

export {};
